"""
Django settings for intern_portal project.

Generated by 'django-admin startproject' using Django 6.1.
"""

import os
import sys
from pathlib import Path

# ============================================================
# BASE DIRECTORY
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# ============================================================
# LOAD .ENV LOCALLY IF AVAILABLE
# ============================================================

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass


# ============================================================
# SECURITY
# ============================================================

SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-local-development-key'
)

DEBUG = os.environ.get(
    'DEBUG',
    'True'
).lower() in ('true', '1', 't')


# ============================================================
# HOSTS
# ============================================================

allowed_hosts_env = os.environ.get('ALLOWED_HOSTS', '')

ALLOWED_HOSTS = (
    [h.strip() for h in allowed_hosts_env.split(',') if h.strip()]
    if allowed_hosts_env
    else ['127.0.0.1', 'localhost', '.vercel.app', '.onrender.com', 'your-domain.com']
)


# ============================================================
# CSRF
# ============================================================

csrf_origins_env = os.environ.get('CSRF_TRUSTED_ORIGINS', '')

CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in csrf_origins_env.split(',')
    if origin.strip()
] or [
    'https://*.vercel.app',
    'https://*.onrender.com',
]

# ============================================================
# APPLICATIONS
# ============================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',  # Add WhiteNoise for static files

    # Local apps
    'accounts',
    'academics',
    'dashboard',
]

AUTH_USER_MODEL = 'accounts.User'


# ============================================================
# AUTHENTICATION
# ============================================================

AUTHENTICATION_BACKENDS = [
    'accounts.backends.FlexAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add WhiteNoise middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ============================================================
# URL / TEMPLATES / WSGI
# ============================================================

ROOT_URLCONF = 'intern_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'intern_portal.wsgi.application'


# ============================================================
# DATABASE SETUP (PRODUCTION SAFE - PSYCOPG 3)
# ============================================================

DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()

if DATABASE_URL:
    from urllib.parse import urlparse, unquote

    if DATABASE_URL.startswith('postgres://'):
        DATABASE_URL = DATABASE_URL.replace('postgres://', 'postgresql://', 1)

    url = urlparse(DATABASE_URL)

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg3',  # Uses psycopg 3
            'NAME': url.path[1:],
            'USER': url.username,
            'PASSWORD': unquote(url.password) if url.password else '',
            'HOST': url.hostname,
            'PORT': url.port or 5432,
            'CONN_MAX_AGE': 600,
            'OPTIONS': {
                'sslmode': 'require',
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# ============================================================
# PASSWORD VALIDATION
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator',
    },
    {
        'NAME':
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator',
    },
]


# ============================================================
# INTERNATIONALIZATION
# ============================================================

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ============================================================
# STATIC FILES
# ============================================================

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# WhiteNoise configuration for production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# ============================================================
# MEDIA FILES
# ============================================================

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


# ============================================================
# SUPABASE STORAGE (OPTIONAL - WARN INSTEAD OF RAISE ERROR)
# ============================================================

SUPABASE_URL = os.environ.get('SUPABASE_URL')

SUPABASE_SECRET_KEY = os.environ.get('SUPABASE_SECRET_KEY')

SUPABASE_STORAGE_BUCKET = os.environ.get(
    'SUPABASE_STORAGE_BUCKET',
    'course-outline'
)

# Check if Supabase is configured - warn but don't fail
SUPABASE_CONFIGURED = bool(
    SUPABASE_URL and SUPABASE_SECRET_KEY
)

if not SUPABASE_CONFIGURED:
    print("Warning: Supabase storage is not configured. Some features may not work.", file=sys.stderr)


# ============================================================
# VERCEL / PRODUCTION SETTINGS
# ============================================================

IS_VERCEL = (
    os.environ.get('VERCEL') == '1'
    or bool(os.environ.get('VERCEL_URL'))
)

# Don't raise errors for missing Supabase - just warn

# ============================================================
# LOGIN / LOGOUT
# ============================================================

LOGIN_URL = 'accounts:login'

LOGIN_REDIRECT_URL = 'dashboard:router'

LOGOUT_REDIRECT_URL = 'accounts:login'


# ============================================================
# DEFAULT MODEL FIELD
# ============================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ============================================================
# EMAIL
# ============================================================

EMAIL_BACKEND = (
    'django.core.mail.backends.console.EmailBackend'
)


# ============================================================
# PRODUCTION SECURITY
# ============================================================

if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    
    # Additional production settings
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True