from django.contrib.auth import login
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import SetPasswordForm
from django.db.models import Q
from django.shortcuts import redirect, render
from django.contrib.auth import logout
from django.shortcuts import render
from django.views.decorators.http import require_POST

from .forms import FlexAuthenticationForm, TokenActivationForm
from .models import InternProfile, SupervisorProfile, User


class CustomLoginView(LoginView):
    template_name = 'accounts/login.html'
    authentication_form = FlexAuthenticationForm


def activate_account(request):
    """
    Public account activation view.
    Validates a one-time activation token (or issued Intern ID) with 48-hour expiration.
    Once used, the token is invalidated and the account is activated.
    """
    token_param = request.GET.get('token', '').strip()
    id_param = request.GET.get('intern_id', '').strip()

    initial_data = {}
    if token_param:
        initial_data['token_or_id'] = token_param
    elif id_param:
        initial_data['token_or_id'] = id_param

    if request.method == 'POST':
        form = TokenActivationForm(request.POST)
        if form.is_valid():
            token_or_id = form.cleaned_data['token_or_id'].strip()
            email = form.cleaned_data['email'].strip().lower()
            password = form.cleaned_data['password']

            # Lookup by activation_token OR intern_id
            profile = (
                InternProfile.objects.filter(
                    Q(activation_token=token_or_id) | Q(intern_id__iexact=token_or_id),
                    is_activated=False
                ).first()
            )

            if not profile:
                form.add_error('token_or_id', 'Invalid or already activated token/ID.')
            elif profile.activation_token and not profile.is_token_valid(profile.activation_token):
                form.add_error('token_or_id', 'This activation token has expired (valid for 48 hours). Please request a new activation link from your administrator.')
            elif User.objects.filter(email__iexact=email).exists():
                form.add_error('email', 'This email address is already in use.')
            else:
                # 1. Base username derived from intern_id
                base_username = profile.intern_id.lower()
                username = base_username
                counter = 1

                # 2. Guarantee username uniqueness before calling create_user
                while User.objects.filter(username__iexact=username).exists():
                    username = f"{base_username}_{counter}"
                    counter += 1

                name_parts = profile.full_name.split(' ')
                first_name = name_parts[0]
                last_name = ' '.join(name_parts[1:]) if len(name_parts) > 1 else ''

                user = User.objects.create_user(
                    username=username,
                    email=email,
                    password=password,
                    role=User.ROLE_INTERN,
                    first_name=first_name,
                    last_name=last_name,
                )
                profile.user = user
                profile.is_activated = True
                profile.activation_token = None  # Invalidate token immediately
                profile.save()

                login(request, user, backend='accounts.backends.FlexAuthBackend')
                return redirect('dashboard:router')

    else:
        form = TokenActivationForm(initial=initial_data)

    return render(request, 'accounts/activate.html', {
        'form': form,
        'token_param': token_param or id_param
    })

def activate_supervisor_account(request):
    """
    Allows a supervisor to activate their account using the
    one-time activation link generated by the administrator.
    """

    token = request.GET.get('token', '').strip()

    profile = (
        SupervisorProfile.objects
        .select_related('user')
        .filter(
            activation_token=token,
            is_activated=False
        )
        .first()
    )

    # Invalid or already-used link
    if not token or not profile:
        return render(
            request,
            'accounts/supervisor_activate.html',
            {
                'activation_error':
                    'This activation link is invalid or has already been used.'
            },
            status=400
        )

    # Expired link
    if not profile.is_token_valid(token):
        return render(
            request,
            'accounts/supervisor_activate.html',
            {
                'activation_error':
                    'This activation link has expired. '
                    'Please ask the administrator for a new activation link.'
            },
            status=400
        )

    user = profile.user

    if request.method == 'POST':

        form = SetPasswordForm(user, request.POST)

        if form.is_valid():

            # Set supervisor's chosen password
            form.save()

            # Enable login
            user.is_active = True
            user.save(update_fields=['password', 'is_active'])

            # Mark activation complete
            profile.is_activated = True
            profile.activation_token = None
            profile.token_created_at = None

            profile.save(
                update_fields=[
                    'is_activated',
                    'activation_token',
                    'token_created_at'
                ]
            )

            # Log supervisor in
            login(
                request,
                user,
                backend='accounts.backends.FlexAuthBackend'
            )

            return redirect('dashboard:router')

    else:
        form = SetPasswordForm(user)

    return render(
        request,
        'accounts/supervisor_activate.html',
        {
            'form': form,
            'profile': profile,
            'supervisor_user': user
        }
    )
    
@require_POST
def logout_view(request):
    logout(request)

    return render(
        request,
        'accounts/logged_out.html'
    )