# Generated by Django 6.1 on 2026-09-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_internprofile_custom_supervisor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Unchecked = removed by supervisor; hides intern without deleting their history.'),
        ),
    ]
