# Generated by Django 6.1 on 2026-09-02 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_internprofile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internprofile',
            name='is_active',
        ),
    ]
