# Generated by Django 6.1 on 2026-09-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_internprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorprofile',
            name='activation_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supervisorprofile',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
