# Generated by Django 5.0.7 on 2026-09-06 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_tasks', to='accounts.internprofile'),
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
            ],
            options={
                'verbose_name': 'Task Submission',
                'verbose_name_plural': 'Task Submissions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('academics.dailytask',),
        ),
        migrations.AddField(
            model_name='departmentassignment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.department'),
        ),
        migrations.AddField(
            model_name='departmentassignment',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to='accounts.internprofile'),
        ),
        migrations.AddField(
            model_name='internshipweek',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='academics.department'),
        ),
        migrations.AddField(
            model_name='topic',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='academics.internshipweek'),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='academics.topic'),
        ),
    ]
