# Generated by Django 6.1 on 2026-08-29 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipweek',
            name='intern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='accounts.internprofile'),
        ),
        migrations.AddField(
            model_name='topic',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='academics.internshipweek'),
        ),
        migrations.AddField(
            model_name='dailytask',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='academics.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='internshipweek',
            unique_together={('intern', 'week_number')},
        ),
    ]
