# Generated by Django 5.0.7 on 2026-08-31 17:56

import academics.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0002_internprofile_activation_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytask',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='internshipweek',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_text', models.TextField(blank=True)),
                ('attached_file', models.FileField(blank=True, null=True, upload_to='submissions/', validators=[academics.models.validate_submission_file])),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed / Approved'), ('revision_requested', 'Revision Requested')], default='submitted', max_length=25)),
                ('feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to='accounts.internprofile')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academics.dailytask')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
