# Generated by Django 5.0.7 on 2026-09-06 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipweek',
            name='title',
        ),
        migrations.AddField(
            model_name='internshipweek',
            name='intern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='accounts.internprofile'),
        ),
        migrations.AlterField(
            model_name='internshipweek',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.department'),
        ),
        migrations.AlterField(
            model_name='internshipweek',
            name='week_number',
            field=models.PositiveIntegerField(),
        ),
    ]
