# Generated by Django 5.0.7 on 2026-09-06 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_remove_internshipweek_title_internshipweek_intern_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='coordinator',
            field=models.ForeignKey(blank=True, help_text='Coordinator responsible for interns rotating through this department.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='accounts.coordinatorprofile', verbose_name='Department Coordinator'),
        ),
    ]
