# Generated by Django 6.1 on 2026-09-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_dailytask_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipweek',
            name='course_outline_file',
            field=models.FileField(blank=True, null=True, upload_to='course_outlines/'),
        ),
        migrations.AddField(
            model_name='internshipweek',
            name='course_outline_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internshipweek',
            name='course_outline_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
