# Generated by Django 5.0.7 on 2026-09-06 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_department_coordinator'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipweek',
            name='supervisor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_weeks', to='accounts.coordinatorprofile'),
        ),
        migrations.AlterField(
            model_name='internshipweek',
            name='course_outline_file',
            field=models.FileField(blank=True, null=True, upload_to='outlines/'),
        ),
        migrations.AlterField(
            model_name='internshipweek',
            name='course_outline_text',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='internshipweek',
            name='course_outline_title',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='internshipweek',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.department'),
        ),
        migrations.AlterField(
            model_name='internshipweek',
            name='intern',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_weeks', to='accounts.internprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internshipweek',
            name='week_number',
            field=models.IntegerField(),
        ),
    ]
