# Generated by Django 5.0.7 on 2026-09-08 05:25

import intern_portal.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_internshipweek_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipweek',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailytask',
            name='attached_file',
            field=models.FileField(blank=True, null=True, storage=intern_portal.supabase_storage.SupabaseStorage(), upload_to='task_submissions/'),
        ),
        migrations.AlterField(
            model_name='internshipweek',
            name='course_outline_file',
            field=models.FileField(blank=True, null=True, storage=intern_portal.supabase_storage.SupabaseStorage(), upload_to='outlines/'),
        ),
    ]
