# Generated by Django 5.0.7 on 2026-09-05 03:18

import intern_portal.supabase_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_internshipweek_course_outline_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipweek',
            name='course_outline_file',
            field=models.FileField(blank=True, null=True, storage=intern_portal.supabase_storage.SupabaseStorage(), upload_to='course_outlines/'),
        ),
    ]
