# Generated by Django 5.0.7 on 2026-09-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_internshipweek_is_locked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internshipweek',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='internshipweek',
            name='is_locked_override',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
